### ISSUE TITLE
[4pt] Create a Movie class in a separate .rb file.

### ISSUE THREAD

**Issue by Mithi-code** [Mithi-code/ruby-capstone#35]
- Create Movie class in a separate .rb file.
- Create Source class with an association to the Item class (in a separate .rb file).
- All Movie class properties visible in the diagram should be defined and set up in the constructor method.
- All Source class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
  -- add_item method in the Source class
  -- should take an instance of the Item class as an input
  -- should add the input item to the collection of items
  -- should add self as a property of the item object (by using the correct setter from the item object)
- can_be_archived?() in the Movie class
  -- should override the method from the parent class
  -- should return true if the parent's method returns true OR if silent equals true
  -- otherwise, it should return false.

**Comment by rachidelaid** [comment]
Hi @Mithi-code, this task is done you can start the review here #37
